[pytest]
testpaths = tests
norecursedirs =
    cpp/external
    build
    .venv
    PrimePyVenv
    primepie/core
python_files = test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = -ra